### ISSUE TITLE
Decryption does not work...

### ISSUE THREAD

**Issue by BigPanda97** [jedisct1/java-aegis#1]
For me, encryption works, but decryption always throws this:

`VerificationFailedException []
	at com.encryption.aegis.Aegis256.decryptDetached(Aegis256.java:170)
	at com.encryption.aegis.Aegis256.decrypt(Aegis256.java:181)`

Have you tested it? Maybe you have some test vectors for this cipher?

**Comment by jedisct1** [comment]
Hi!

And thanks for reporting this!

There was indeed an issue when the length of messages were not a multiple of the block size.

It should have been fixed now.

Can you confirm that the current code works for you?

**Comment by BigPanda97** [comment]
> Can you confirm that the current code works for you?

Yes, encryption and decryption works now! But there is one question left: How can I encrypt and authenticate data without the additional unencrypted data? On other ciphers, you can just leave "byte[] ad = null;", but here this throws a "Exception in thread "main" java.lang.NullPointerException: Cannot read the array length because "ad" is null".
And if I try using "byte[] ad = {0};", it throws:
Exception in thread "main" VerificationFailedException []
	at com.encryption.aegis.Aegis256.decryptDetached(Aegis256.java:163)
	at com.encryption.aegis.Aegis256.decrypt(Aegis256.java:174)

**Comment by jedisct1** [comment]
Set the `ad` to an empty array (`{0}` is not an empty array, it's an array with a zero).

**Comment by jedisct1** [comment]
I made a change to allow "null" to be used for the ad or message.

**Comment by BigPanda97** [comment]
> Set the ad to an empty array ({0} is not an empty array, it's an array with a zero).

Correct, I missed that.

> I made a change to allow "null" to be used for the ad or message.

Thanks! Very very nice.
