### ISSUE TITLE
Some issues with the test vectors...

### ISSUE THREAD

**Issue by BigPanda97** [jedisct1/java-aegis#2]
I tried this: https://datatracker.ietf.org/doc/draft-irtf-cfrg-aegis-aead/ AEGIS test vectors and found some strange things:

- Encryption without AdditionalData passes the test vectors for me (both 128L and 256)
- Encryption with small AD ("0001020304050607") fails the test vectors, but "works" (gives you some output)  (both 128L and 256)
- Encryption with more AD ("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20212223242526272829") throws: `Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 32 out of bounds for length 16
	at com.test.aegis.Aegis256.encryptDetached(Aegis256.java:91)
	at com.test.aegis.Aegis256.encrypt(Aegis256.java:122)`

This happens for both versions (128L and 256).

Also btw. did you receive my e-mail about Forro last Tuesday?

**Comment by jedisct1** [comment]
Good catch, thank you!

This was due to a typo and https://github.com/jedisct1/aegis-java/commit/dc76b75398479d770102c6354c97ab410b49c253 should fix it.

**Comment by BigPanda97** [comment]
@jedisct1 thanks! I'll check it against all the test vectors later.

> Also btw. did you receive my e-mail about Forro last Tuesday?

Any news on this? (Maybe the email got stuck in the spam filter?)
